name: mno_navigator
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/iridium
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  dartx: ^1.1.0
  dfunc: ^0.8.1
  equatable: ^2.0.5
  fimber: ^0.6.6
  flutter_bloc: ^8.1.1
  flutter_inappwebview: ^5.7.2+3
  flutter_spinkit: ^5.1.0
  photo_view: ^0.14.0
  preload_page_view: ^0.1.6
  rxdart: ^0.27.7
  universal_io: ^2.0.4

  mno_commons:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: commons
  mno_server:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: server
  mno_shared:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: shared
  mno_streamer:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: streamer
  mno_webview:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: webview

dev_dependencies:
  test: ^1.22.2
  lints: ^2.0.1

dependency_overrides:
  collection: ^1.17.0

flutter:
  assets:
    - assets/readium/assets/
    - assets/readium/divina/
    - assets/readium/fonts/
    - assets/readium/readium-css/
    - assets/readium/readium-css/cjk-horizontal/
    - assets/readium/readium-css/cjk-vertical/
    - assets/readium/readium-css/fonts/
    - assets/readium/readium-css/rtl/
    - assets/readium/scripts/
    - assets/xpub-shared-js/
    - assets/xpub-js/
    - assets/xpub-js/controllers/
    - assets/xpub-js/model/
    - assets/xpub-js/utils/
