name: mno_streamer
version: 0.1.1
description: Streamer API and multiple file parsers (PDF, CBZ, Epub) for Dart.
homepage: https://github.com/Mantano/mno_streamer_dart
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dartx: ^1.1.0
  dfunc: ^0.8.1
  fimber: ^0.6.6
  image: ^4.0.11
  universal_io: ^2.0.4
  xml: ^6.2.2
  mno_commons:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: commons
  mno_shared:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: shared
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
