name: iridium_app
description: A Flutter app for eBooks
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Managed by CodeMagic. See https://docs.codemagic.io/configuration/build-versioning/
# version: 0.0.1+2

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  iridium_reader_widget:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: reader_widget
  mno_commons:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/commons
  mno_navigator:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/navigator
  mno_opds:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/opds
  mno_shared:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/shared
  mno_webview:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/webview
  mno_lcp:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/lcp
  mno_streamer:
    git:
      url: https://github.com/lvaniscak/iridium.git
      path: components/streamer

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dartx: ^1.1.0
  dfunc: ^0.8.1
  dio: ^4.0.6
  fimber: ^0.6.6
  flutter_fimber: ^0.6.5
  flutter_font_icons: ^2.2.5
  flutter_inappwebview: ^5.7.2+3
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1
  json_theme: ^4.0.3+4
  objectdb: ^1.2.1+1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  sqflite: ^2.2.3
  sqflite_common_ffi: ^2.2.1
  universal_io: ^2.0.4
  uuid: ^3.0.7
  package_info_plus_web: ^2.0.0
  url_launcher_web: ^2.0.14
  file_picker: ^5.2.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.17.0
  intl: ^0.18.0
  path: ^1.8.3
  shared_preferences_windows: 2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/appainter_light_theme.json
    - assets/appainter_dark_theme.json
